{{- if .Values.createNamespace | default true }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    name: {{ .Release.Namespace }}
    {{- include "cloudflared.labels" . | nindent 4 }}
{{- end }}
