{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudflared.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: metrics
    port: {{ .Values.service.port }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "cloudflared.selectorLabels" . | nindent 4 }}
{{- end -}}
