# statefulset.yaml

# A "headless" service is required by the StatefulSet for network identity.
# It doesn't load balance; it just gives each pod a stable DNS name (e.g., vault-0.vault-internal.vault.svc.cluster.local)
apiVersion: v1
kind: Service
metadata:
  name: vault-internal
  namespace: vault
spec:
  # clusterIP: None makes this a "headless" service
  clusterIP: None
  selector:
    app: vault
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: https-internal
      port: 8201
      targetPort: 8201
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: vault
spec:
  # The serviceName must match the name of the headless service above
  serviceName: "vault-internal"
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault
      initContainers:
      - name: vault-init
        image: busybox:1.35
        command: ['sh', '-c', 'chown -R 100:1000 /vault/data && chmod -R 755 /vault/data']
        volumeMounts:
        - name: vault-storage
          mountPath: /vault/data
        securityContext:
          runAsUser: 0
      securityContext:
        runAsUser: 100
        fsGroup: 1000
      containers:
      - name: vault
        image: hashicorp/vault:latest
        args: ["vault", "server", "-config=/vault/config/vault.hcl"]
        ports:
        - containerPort: 8200
          name: vault-port
        - containerPort: 8201
          name: cluster-port
        env:
        - name: VAULT_ADDR
          value: "http://127.0.0.1:8200" # Use localhost for readiness/liveness probes
        - name: VAULT_API_ADDR
          value: "http://$(POD_IP):8200"
        - name: VAULT_CLUSTER_ADDR
          value: "http://$(POD_IP):8201"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SKIP_SETCAP
          value: "true"
        volumeMounts:
        - name: vault-storage
          mountPath: /vault/data
        - name: vault-config
          mountPath: /vault/config
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        readinessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true&sealedcode=200&uninitcode=200
            port: 8200
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true&sealedcode=200&uninitcode=200
            port: 8200
          initialDelaySeconds: 30
          periodSeconds: 30

      # Auto-unseal sidecar container (no changes needed here)
      - name: vault-unsealer
        image: hashicorp/vault:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          echo "Starting Vault auto-unsealer..."
          while ! wget -q --spider http://127.0.0.1:8200/v1/sys/health?sealedcode=200 2>/dev/null; do
            echo "Waiting for Vault to start..."
            sleep 5
          done
          echo "Vault is reachable, starting monitoring loop..."
          while true; do
            SEALED=$(wget -qO- http://127.0.0.1:8200/v1/sys/seal-status | grep -o '"sealed":[^,}]*' | cut -d: -f2 | tr -d ' "')
            if [ "$SEALED" = "true" ]; then
              echo "Vault is sealed, attempting to unseal..."
              KEY1=$(cat /vault/keys/key1)
              KEY2=$(cat /vault/keys/key2)
              KEY3=$(cat /vault/keys/key3)
              vault operator unseal "$KEY1"
              vault operator unseal "$KEY2"
              vault operator unseal "$KEY3"
              echo "Unseal attempt completed."
            else
              echo "Vault is unsealed."
            fi
            sleep 60
          done
        env:
        - name: VAULT_ADDR
          value: "http://127.0.0.1:8200"
        volumeMounts:
        - name: vault-unseal-keys
          mountPath: /vault/keys
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

      volumes:
      # These volumes are mounted into the containers. The vault-storage volume
      # is backed by the PersistentVolumeClaim defined in volumeClaimTemplates.
      - name: vault-config
        configMap:
          name: vault-config
      - name: vault-unseal-keys
        secret:
          secretName: vault-unseal-keys

  # This template defines the PersistentVolumeClaim that will be created
  # for each pod in the StatefulSet.
  volumeClaimTemplates:
  - metadata:
      name: vault-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
      # storageClassName: your-storage-class # Uncomment and specify if needed
