# cloudflared-values.yaml
cloudflared:
  # Your tunnel token from Step 1
  token: "eyJhIjoiMGNhMTkyMTI3YjY4OTM5Mjc4Yjc2MzUwMDkyMmIxODUiLCJ0IjoiYjI5ZWI3ZGItZDc1Ny00ZDgwLThjMTgtYWYwYmIwNzU0MWJhIiwicyI6IllUZzVNMlprWmpFdE9XUmhNaTAwWldNMExUZ3dORGt0WWpSbVpqWmxNak0zTVRZMCJ9"
  
  # Tunnel configuration
  tunnelName: "homelab-k3s"
  
  # Resource limits
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Number of replicas for high availability
replicaCount: 2

# Image configuration
image:
  repository: cloudflare/cloudflared
  tag: "2025.8.0"
  pullPolicy: IfNotPresent

# Service account
serviceAccount:
  create: true
  name: cloudflared

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532

# Security context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL

# Node selector (optional - pin to specific nodes)
# nodeSelector:
#   kubernetes.io/hostname: homelab1

# Tolerations (optional)
# tolerations: []

# Affinity (optional - spread across nodes)
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - cloudflared
        topologyKey: kubernetes.io/hostname

# Environment variables
env:
  - name: TUNNEL_METRICS
    value: "0.0.0.0:2000"
  - name: TUNNEL_LOGLEVEL
    value: "info"

# Additional arguments
args:
  - tunnel
  - --no-autoupdate
  - --metrics
  - "0.0.0.0:2000"
  - run

# Monitoring (if you have Prometheus)
serviceMonitor:
  enabled: false
  # interval: 30s
  # path: /metrics
  # port: metrics
