apiVersion: v1
kind: ServiceAccount
metadata:
  name: bank-vaults-operator
  namespace: bank-vaults
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bank-vaults-operator
rules:
- apiGroups: ["vault.banzaicloud.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets", "configmaps", "pods", "services", "endpoints", "persistentvolumeclaims"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bank-vaults-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bank-vaults-operator
subjects:
- kind: ServiceAccount
  name: bank-vaults-operator
  namespace: bank-vaults
