apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx                    # ← Application name in ArgoCD UI
  namespace: argocd              # ← ALWAYS 'argocd' (where ArgoCD apps live)
spec:
  project: default               # ← ArgoCD project (usually 'default')
  
  # SOURCE: Where to get the manifests FROM
  source:
    repoURL: 'https://github.com/user/repo.git'  # ← Your Git repository
    path: 'apps/nginx'                           # ← Folder in repo to deploy
    targetRevision: HEAD                         # ← Git branch/tag
  
  # DESTINATION: Where to deploy TO
  destination:
    server: 'https://kubernetes.default.svc'     # ← Kubernetes cluster
    namespace: nginx-homelab                     # ← Target namespace for your app
  
  # SYNC POLICY: How to deploy
  syncPolicy:
    automated:
      prune: true              # ← Delete resources not in Git
      selfHeal: true           # ← Auto-fix manual changes
    syncOptions:
    - CreateNamespace=true     # ← Create namespace if missing
