apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/your-argocd-repo.git
    targetRevision: HEAD
    path: apps/nginx/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-prod
  syncPolicy:
    automated:
      prune: false  # More careful with production
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
