apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-homelab
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: 'https://github.com/PawelHejlig/homelab_k8s_go_argocd_helm_monitoring.git'
    path: 'apps/nginx'
    targetRevision: HEAD
    # Add this section to tell ArgoCD to use Kustomize
    kustomize: {}  # This tells ArgoCD to look for kustomization.yaml and build
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
