apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zabbix-agent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: zabbix-agent
    component: monitoring
spec:
  project: default
  source:
    repoURL: https://your-git-repo.com/your-org/k8s-manifests  # Replace with your Git repo URL
    path: zabbix-agent
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: zabbix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5
