# File: zabbix/Chart.yaml
# Helm chart metadata for ArgoCD
apiVersion: v2
name: zabbix-deployment
description: Zabbix monitoring deployment
version: 1.0.0
dependencies:
- name: zabbix
  version: 3.0.0
  repository: https://zabbix-community.github.io/helm-zabbix
