apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-agent-config
  namespace: zabbix
  labels:
    app: zabbix-agent
    component: monitoring
data:
  zabbix_agent2.conf: |
    # Zabbix Agent 2 Configuration
    Server=zabbix-zabbix-server.zabbix.svc.cluster.local,192.168.88.233
    ServerActive=zabbix-zabbix-server.zabbix.svc.cluster.local:10051
    Hostname=homelab1
    ListenPort=10050
    
    # Logging
    LogType=console
    DebugLevel=3
    
    # Performance settings
    Timeout=30
