apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-agent-config
  namespace: zabbix
  labels:
    app: zabbix-agent
    component: monitoring
data:
  zabbix_agent2.conf: |
    # Zabbix Agent 2 Configuration
    Server=zabbix-zabbix-server.zabbix.svc.cluster.local,10.42.0.0/16,192.168.88.0/24,127.0.0.1
    ServerActive=zabbix-zabbix-server.zabbix.svc.cluster.local:10051
    Hostname=homelab1
    ListenPort=10050

    # Logging
    LogType=console
    DebugLevel=3

    # Performance settings
    Timeout=30

    # Include your custom user parameters
    Include=/etc/zabbix/zabbix_agent2.d/kubernetes-monitoring.conf

  kubernetes-monitoring.conf: |
    # ───────────────────────────────
    # Kubernetes Pods - Global
    # ───────────────────────────────
    UserParameter=k8s.pods.total,kubectl get pods -A --no-headers 2>/dev/null | wc -l || echo "0"
    UserParameter=k8s.pods.running,kubectl get pods -A --field-selector=status.phase=Running --no-headers 2>/dev/null | wc -l || echo "0"
    UserParameter=k8s.pods.pending,kubectl get pods -A --field-selector=status.phase=Pending --no-headers 2>/dev/null | wc -l || echo "0"
    UserParameter=k8s.pods.failed,kubectl get pods -A --field-selector=status.phase=Failed --no-headers 2>/dev/null | wc -l || echo "0"
    UserParameter=k8s.pods.succeeded,kubectl get pods -A --field-selector=status.phase=Succeeded --no-headers 2>/dev/null | wc -l || echo "0"
    UserParameter=k8s.pods.unknown,kubectl get pods -A --no-headers 2>/dev/null | grep -vcE "Running|Pending|Succeeded|Failed" || echo "0"

    # ───────────────────────────────
    # Pods by Namespace
    # ───────────────────────────────
    UserParameter=k8s.pods.namespace[*],kubectl get pods -n $1 --no-headers 2>/dev/null | wc -l || echo "0"
    UserParameter=k8s.pods.running.namespace[*],kubectl get pods -n $1 --field-selector=status.phase=Running --no-headers 2>/dev/null | wc -l || echo "0"
    UserParameter=k8s.pods.failed.namespace[*],kubectl get pods -n $1 --field-selector=status.phase=Failed --no-headers 2>/dev/null | wc -l || echo "0"

    # ───────────────────────────────
    # Pods Detailed Metrics - FIXED
    # ───────────────────────────────

    UserParameter=k8s.pod.cpu[*],/usr/local/bin/kubectl top pod $1 -n $2 --no-headers 2>/dev/null | awk '{print $$2}' | sed 's/m$$//' || echo "0"
    UserParameter=k8s.pod.mem[*],/usr/local/bin/kubectl top pod $1 -n $2 --no-headers 2>/dev/null | awk '{print $$3}' | sed 's/Mi$$//' || echo "0"

    # Restarts
    UserParameter=k8s.pod.restarts[*],kubectl get pod $1 -n $2 -o jsonpath='{.status.containerStatuses[*].restartCount}' 2>/dev/null || echo "0"
    # Pod phase
    UserParameter=k8s.pod.phase[*],kubectl get pod $1 -n $2 -o jsonpath='{.status.phase}' 2>/dev/null || echo "Unknown"
    # Pod age in seconds
    UserParameter=k8s.pod.age[*],kubectl get pod $1 -n $2 -o jsonpath='{.metadata.creationTimestamp}' 2>/dev/null | xargs -I{} date -d {} +%s | awk -v now=$(date +%s) '{print now - $1}' || echo "0"

    # ───────────────────────────────
    # Pods Discovery (for LLD in Zabbix)
    # ───────────────────────────────
    UserParameter=k8s.pods.discovery,kubectl get pods -A -o jsonpath='{range .items[*]}{"{\"{#PODNAME}\":\""@.metadata.name\"\,\"{#NAMESPACE}\":\""@.metadata.namespace"\"},\n"}{end}' 2>/dev/null | sed '$ s/,$//' | awk 'BEGIN{print "{\"data\":["}{print}{print "]"}' || echo '{"data":[]}'

    # ───────────────────────────────
    # Node Metrics
    # ───────────────────────────────
    UserParameter=k8s.nodes.total,kubectl get nodes --no-headers 2>/dev/null | wc -l || echo "0"
    UserParameter=k8s.nodes.ready,kubectl get nodes --no-headers 2>/dev/null | grep -c " Ready " || echo "0"
    UserParameter=k8s.nodes.notready,kubectl get nodes --no-headers 2>/dev/null | grep -c " NotReady " || echo "0"

    # ───────────────────────────────
    # Namespaces / Events
    # ───────────────────────────────
    UserParameter=k8s.namespaces.total,kubectl get namespaces --no-headers 2>/dev/null | wc -l || echo "0"
    UserParameter=k8s.events.warning,kubectl get events -A --field-selector type=Warning --no-headers 2>/dev/null | wc -l || echo "0"
    UserParameter=k8s.events.normal,kubectl get events -A --field-selector type=Normal --no-headers 2>/dev/null | wc -l || echo "0"
