apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zabbix-agent
  namespace: zabbix
  labels:
    app: zabbix-agent
    component: monitoring
spec:
  selector:
    matchLabels:
      app: zabbix-agent
  template:
    metadata:
      labels:
        app: zabbix-agent
        component: monitoring
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: zabbix-agent
        image: zabbix/zabbix-agent2:6.4-alpine-latest
        env:
        - name: ZBX_HOSTNAME
          value: "homelab1"
        - name: ZBX_SERVER_HOST
          value: "zabbix-zabbix-server.zabbix.svc.cluster.local"
        - name: ZBX_PASSIVE_ALLOW
          value: "true"
        - name: ZBX_ACTIVE_ALLOW
          value: "true"
        ports:
        - containerPort: 10050
          hostPort: 10050
          name: zabbix-agent
          protocol: TCP
        securityContext:
          privileged: true
          runAsUser: 0
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: agent-config
          mountPath: /etc/zabbix/zabbix_agent2.d
          subPath: zabbix_agent2.conf
          readOnly: true
        livenessProbe:
          tcpSocket:
            port: 10050
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 10050
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: proc
        hostPath:
          path: /proc
          type: Directory
      - name: sys
        hostPath:
          path: /sys
          type: Directory
      - name: agent-config
        configMap:
          name: zabbix-agent-config
          defaultMode: 0644
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
