apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent
  namespace: zabbix
  labels:
    app: zabbix-agent
    component: monitoring
spec:
  type: ClusterIP
  clusterIP: None  # Headless service
  selector:
    app: zabbix-agent
  ports:
  - name: zabbix-agent
    port: 10050
    targetPort: 10050
    protocol: TCP
