# This is the file at: apps/argo-apps.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # ArgoCD applications should be in the argocd namespace, not the target namespace
  name: nginx
  namespace: argocd  # Changed from 'nginx' to 'argocd'
  # Adding a finalizer is a good practice for the App of Apps pattern
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/PawelHejlig/homelab_k8s_go_argocd_helm_monitoring.git'
    # Fixed path - removed redundant directory name
    path: 'apps/nginx'  # Changed from 'homelab_k8s_go_argocd_helm_monitoring/apps/nginx/'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    # This is the namespace where the NGINX pods will be deployed
    namespace: nginx-homelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
