apiVersion: v2
name: cloudflared
description: Cloudflare Tunnel (cloudflared) Helm chart
type: application
version: 0.1.0
appVersion: "2025.8.0"
keywords:
  - cloudflare
  - tunnel
  - proxy
home: https://github.com/cloudflare/cloudflared
sources:
  - https://github.com/cloudflare/cloudflared
maintainers:
  - name: homelab
