apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault
      initContainers:
      - name: vault-init
        image: busybox:1.35
        command: ['sh', '-c', 'chown -R 100:1000 /vault/data && chmod -R 755 /vault/data']
        volumeMounts:
        - name: vault-storage
          mountPath: /vault/data
        securityContext:
          runAsUser: 0
      securityContext:
        runAsUser: 100
        fsGroup: 1000
      containers:
      - name: vault
        image: hashicorp/vault:1.15.2
        args: ["vault", "server", "-config=/vault/config/vault.hcl"]
        ports:
        - containerPort: 8200
          name: vault-port
        - containerPort: 8201
          name: cluster-port
        env:
        - name: VAULT_ADDR
          value: "http://vault-service.vault.svc.cluster.local:8200"
        - name: SKIP_SETCAP
          value: "true"
        volumeMounts:
        - name: vault-storage
          mountPath: /vault/data
        - name: vault-config
          mountPath: /vault/config
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        readinessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true&sealedcode=200&uninitcode=200
            port: 8200
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true&sealedcode=200&uninitcode=200
            port: 8200
          initialDelaySeconds: 30
          periodSeconds: 30
      # Auto-unseal sidecar container
      - name: vault-unsealer
        image: curlimages/curl:latest
        command: ["/bin/sh", "/scripts/unseal.sh"]
        env:
        - name: UNSEAL_KEY1
          valueFrom:
            secretKeyRef:
              name: vault-unseal-keys
              key: key1
        - name: UNSEAL_KEY2
          valueFrom:
            secretKeyRef:
              name: vault-unseal-keys
              key: key2
        - name: UNSEAL_KEY3
          valueFrom:
            secretKeyRef:
              name: vault-unseal-keys
              key: key3
        volumeMounts:
        - name: unseal-script
          mountPath: /scripts
        
      volumes:
      - name: vault-storage
        persistentVolumeClaim:
          claimName: vault-storage
      - name: vault-config
        configMap:
          name: vault-config
      - name: unseal-script
        configMap:
          name: vault-unseal-script
          defaultMode: 0755
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: vault
#   namespace: vault
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: vault
#   template:
#     metadata:
#       labels:
#         app: vault
#     spec:
#       serviceAccountName: vault
#       initContainers:
#       - name: vault-init
#         image: busybox:1.35
#         command: ['sh', '-c', 'chown -R 100:1000 /vault/data && chmod -R 755 /vault/data']
#         volumeMounts:
#         - name: vault-storage
#           mountPath: /vault/data
#         securityContext:
#           runAsUser: 0
#       securityContext:
#         runAsUser: 100
#         fsGroup: 1000
#       containers:
#       - name: vault
#         image: hashicorp/vault:1.15.2
#         args: ["vault", "server", "-config=/vault/config/vault.hcl"]
#         ports:
#         - containerPort: 8200
#           name: vault-port
#         - containerPort: 8201
#           name: cluster-port
#         env:
#         - name: VAULT_ADDR
#           value: "http://vault-service.vault.svc.cluster.local:8200"
#         - name: SKIP_SETCAP
#           value: "true"
#         volumeMounts:
#         - name: vault-storage
#           mountPath: /vault/data
#         - name: vault-config
#           mountPath: /vault/config
#         securityContext:
#           capabilities:
#             add:
#             - IPC_LOCK
#         readinessProbe:
#           httpGet:
#             path: /v1/sys/health?standbyok=true&sealedcode=200&uninitcode=200
#             port: 8200
#           initialDelaySeconds: 10
#           periodSeconds: 10
#         livenessProbe:
#           httpGet:
#             path: /v1/sys/health?standbyok=true&sealedcode=200&uninitcode=200
#             port: 8200
#           initialDelaySeconds: 30
#           periodSeconds: 30
#       volumes:
#       - name: vault-storage
#         persistentVolumeClaim:
#           claimName: vault-storage
#       - name: vault-config
#         configMap:
#           name: vault-config
