apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault
      initContainers:
      - name: vault-data-init
        image: busybox:1.35
        command: ['sh', '-c', 'chown -R 100:1000 /vault/data && chmod -R 755 /vault/data']
        volumeMounts:
        - name: vault-storage
          mountPath: /vault/data
        securityContext:
          runAsUser: 0
      
      # Auto-unseal init container
      - name: vault-unsealer
        image: curlimages/curl:latest
        command: 
        - /bin/sh
        - -c
        - |
          apk add --no-cache jq
          VAULT_ADDR="http://localhost:8200"
          
          # Wait for vault to start
          echo "Waiting for Vault to start..."
          timeout=300
          while [ $timeout -gt 0 ]; do
            if curl -s ${VAULT_ADDR}/v1/sys/health > /dev/null 2>&1; then
              break
            fi
            echo "Still waiting... ($timeout seconds left)"
            sleep 5
            timeout=$((timeout-5))
          done
          
          # Check if sealed
          HEALTH=$(curl -s ${VAULT_ADDR}/v1/sys/health || echo '{"sealed":true}')
          SEALED=$(echo "$HEALTH" | jq -r '.sealed // true')
          
          if [ "$SEALED" = "true" ]; then
            echo "Vault is sealed, attempting to unseal..."
            
            # Unseal with the 3 keys
            curl -s -X POST -d "{\"key\":\"$UNSEAL_KEY1\"}" ${VAULT_ADDR}/v1/sys/unseal
            curl -s -X POST -d "{\"key\":\"$UNSEAL_KEY2\"}" ${VAULT_ADDR}/v1/sys/unseal  
            curl -s -X POST -d "{\"key\":\"$UNSEAL_KEY3\"}" ${VAULT_ADDR}/v1/sys/unseal
            
            echo "Vault unsealed successfully!"
          else
            echo "Vault is already unsealed"
          fi
        env:
        - name: UNSEAL_KEY1
          valueFrom:
            secretKeyRef:
              name: vault-unseal-keys
              key: key1
        - name: UNSEAL_KEY2
          valueFrom:
            secretKeyRef:
              name: vault-unseal-keys
              key: key2
        - name: UNSEAL_KEY3
          valueFrom:
            secretKeyRef:
              name: vault-unseal-keys
              key: key3
      
      securityContext:
        runAsUser: 100
        fsGroup: 1000
      containers:
      - name: vault
        image: hashicorp/vault:1.15.2
        args: ["vault", "server", "-config=/vault/config/vault.hcl"]
        ports:
        - containerPort: 8200
          name: vault-port
        - containerPort: 8201
          name: cluster-port
        env:
        - name: VAULT_ADDR
          value: "http://vault-service.vault.svc.cluster.local:8200"
        - name: SKIP_SETCAP
          value: "true"
        volumeMounts:
        - name: vault-storage
          mountPath: /vault/data
        - name: vault-config
          mountPath: /vault/config
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        readinessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true&sealedcode=200&uninitcode=200
            port: 8200
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true&sealedcode=200&uninitcode=200
            port: 8200
          initialDelaySeconds: 30
          periodSeconds: 30
      
      volumes:
      - name: vault-storage
        persistentVolumeClaim:
          claimName: vault-storage
      - name: vault-config
        configMap:
          name: vault-config
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: vault
#   namespace: vault
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: vault
#   template:
#     metadata:
#       labels:
#         app: vault
#     spec:
#       serviceAccountName: vault
#       initContainers:
#       - name: vault-init
#         image: busybox:1.35
#         command: ['sh', '-c', 'chown -R 100:1000 /vault/data && chmod -R 755 /vault/data']
#         volumeMounts:
#         - name: vault-storage
#           mountPath: /vault/data
#         securityContext:
#           runAsUser: 0
#       securityContext:
#         runAsUser: 100
#         fsGroup: 1000
#       containers:
#       - name: vault
#         image: hashicorp/vault:1.15.2
#         args: ["vault", "server", "-config=/vault/config/vault.hcl"]
#         ports:
#         - containerPort: 8200
#           name: vault-port
#         - containerPort: 8201
#           name: cluster-port
#         env:
#         - name: VAULT_ADDR
#           value: "http://vault-service.vault.svc.cluster.local:8200"
#         - name: SKIP_SETCAP
#           value: "true"
#         volumeMounts:
#         - name: vault-storage
#           mountPath: /vault/data
#         - name: vault-config
#           mountPath: /vault/config
#         securityContext:
#           capabilities:
#             add:
#             - IPC_LOCK
#         readinessProbe:
#           httpGet:
#             path: /v1/sys/health?standbyok=true&sealedcode=200&uninitcode=200
#             port: 8200
#           initialDelaySeconds: 10
#           periodSeconds: 10
#         livenessProbe:
#           httpGet:
#             path: /v1/sys/health?standbyok=true&sealedcode=200&uninitcode=200
#             port: 8200
#           initialDelaySeconds: 30
#           periodSeconds: 30
#       volumes:
#       - name: vault-storage
#         persistentVolumeClaim:
#           claimName: vault-storage
#       - name: vault-config
#         configMap:
#           name: vault-config
