# In apps/vault/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault
      containers:
      - name: vault
        image: hashicorp/vault:1.15.2
        ports:
        - containerPort: 8200
          name: vault-port
        - containerPort: 8201
          name: cluster-port
        env:
        - name: VAULT_ADDR
          value: "http://127.0.0.1:8200"
        - name: VAULT_API_ADDR
          value: "http://0.0.0.0:8200"
        - name: VAULT_LOCAL_CONFIG
          value: |
            {
              "ui": true,
              "listener": [{
                "tcp": {
                  "address": "0.0.0.0:8200",
                  "tls_disable": 1
                }
              }],
              "storage": {
                "file": {
                  "path": "/vault/data"
                }
              }
            }
        volumeMounts:
        - name: vault-storage
          mountPath: /vault/data
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
      volumes:
      - name: vault-storage
        persistentVolumeClaim:
          claimName: vault-storage
