# In apps/vault/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  # namespace will be set by Argo CD
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault
      containers:
      - name: vault
        image: hashicorp/vault:1.15.2
        ports:
        - containerPort: 8200
          name: vault-port
        - containerPort: 8201
          name: cluster-port
        env:
        - name: VAULT_ADDR
          value: "http://127.0.0.1:8200"
        - name: VAULT_API_ADDR
          value: "http://0.0.0.0:8200"
        # This is now the SINGLE source of config
        - name: VAULT_LOCAL_CONFIG
          valueFrom:
            configMapKeyRef:
              name: vault-config
              key: vault.hcl
        # The conflicting "args" section is gone
        volumeMounts:
        # The conflicting config mount is gone
        - name: vault-storage
          mountPath: /vault/data
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        # ... (probes and resources are fine)
      volumes:
      # The conflicting config volume is gone
      - name: vault-storage
        persistentVolumeClaim:
          claimName: vault-storage
