apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-cloudflared-policy
  namespace: vault
data:
  setup-cloudflared.sh: |
    #!/bin/sh
    set -e

    echo "Writing Cloudflared policy..."
    vault policy write cloudflared - <<EOF
    path "cloudflared/data/cloudflared" {
      capabilities = ["read"]
    }
EOF

    echo "Creating role for SA cloudflared..."
    vault write auth/kubernetes/role/cloudflared-role \
      bound_service_account_names=cloudflared \
      bound_service_account_namespaces=cloudflared \
      policies=cloudflared \
      ttl=1h
---
apiVersion: batch/v1
kind: Job
metadata:
  name: vault-setup-cloudflared
  namespace: vault
spec:
  template:
    spec:
      serviceAccountName: vault
      containers:
      - name: vault-setup
        image: hashicorp/vault:1.15
        command: ["/bin/sh", "/scripts/setup-cloudflared.sh"]
        env:
        - name: VAULT_ADDR
          value: "http://vault-service.vault.svc.cluster.local:8200"
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      restartPolicy: Never
      volumes:
      - name: scripts
        configMap:
          name: vault-cloudflared-policy
