apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-storage
  namespace: vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: your-storage-class  # Uncomment and specify if needed
