apiVersion: v1
kind: Service
metadata:
  name: vault-service
spec:
  # This is the "public phone number" for your service
  type: NodePort
  selector:
    app: vault
  ports:
  - name: vault-port
    port: 8200
    targetPort: 8200
    # The external port for your Vault UI
    nodePort: 30082
  - name: cluster-port
    port: 8201
    targetPort: 8201
    # You can also expose the cluster port if needed, e.g., on 30083
    # nodePort: 30083
