apiVersion: v1
kind: Secret
metadata:
  name: vault-unseal-keys
  namespace: vault
type: Opaque
data:
  # Replace these with your base64-encoded unseal keys
  key1: TcUOJCpLbim+tkpFhNg08CDM2taFUoE9PM1j6FtP/rka
  key2: N/aiR6xlmGEsHjB3Rx8fCjFP+nmzSkYIclhLMvA2CUgv  
  key3: pOWyLiKKFhdPiJFve/sZPxhMElKBzkMg4h9NKgzZYlZM
