apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-unseal-script
  namespace: vault
data:
  unseal.sh: |
    #!/bin/sh
    set -e
    
    VAULT_ADDR="http://localhost:8200"
    
    # Install jq for JSON parsing
    apk add --no-cache jq
    
    # Wait for Vault to be ready
    echo "Waiting for Vault to be ready..."
    until curl -s ${VAULT_ADDR}/v1/sys/health > /dev/null 2>&1; do
      echo "Still waiting for Vault..."
      sleep 5
    done
    
    echo "Vault is ready, checking seal status..."
    
    # Check if already unsealed
    HEALTH_RESPONSE=$(curl -s ${VAULT_ADDR}/v1/sys/health || echo '{"sealed":true}')
    SEALED=$(echo "$HEALTH_RESPONSE" | jq -r '.sealed // true')
    
    if [ "$SEALED" = "true" ]; then
      echo "Vault is sealed, attempting to unseal..."
      
      # Unseal with 3 keys
      echo "Using unseal key 1..."
      curl -s -X POST -d "{\"key\":\"$UNSEAL_KEY1\"}" ${VAULT_ADDR}/v1/sys/unseal
      
      echo "Using unseal key 2..."
      curl -s -X POST -d "{\"key\":\"$UNSEAL_KEY2\"}" ${VAULT_ADDR}/v1/sys/unseal
      
      echo "Using unseal key 3..."  
      curl -s -X POST -d "{\"key\":\"$UNSEAL_KEY3\"}" ${VAULT_ADDR}/v1/sys/unseal
      
      echo "Vault unsealed successfully!"
    else
      echo "Vault is already unsealed"
    fi
    
    # Keep monitoring and auto-unseal if needed
    echo "Starting monitoring loop..."
    while true; do
      sleep 30
      HEALTH_RESPONSE=$(curl -s ${VAULT_ADDR}/v1/sys/health || echo '{"sealed":true}')
      SEALED=$(echo "$HEALTH_RESPONSE" | jq -r '.sealed // true')
      
      if [ "$SEALED" = "true" ]; then
        echo "Vault became sealed, re-unsealing..."
        curl -s -X POST -d "{\"key\":\"$UNSEAL_KEY1\"}" ${VAULT_ADDR}/v1/sys/unseal > /dev/null
        curl -s -X POST -d "{\"key\":\"$UNSEAL_KEY2\"}" ${VAULT_ADDR}/v1/sys/unseal > /dev/null
        curl -s -X POST -d "{\"key\":\"$UNSEAL_KEY3\"}" ${VAULT_ADDR}/v1/sys/unseal > /dev/null
        echo "Re-unsealed successfully"
      fi
    done
