apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  namespace: vault
spec:
  size: 1
  image: hashicorp/vault:1.15.2
  bankVaultsImage: ghcr.io/bank-vaults/bank-vaults:1.21.2

  # How vault stores data
  unsealConfig:
    options:
      preFlightChecks: true
    kubernetes: {}

  # Where to persist data
  volumeClaimTemplates:
    - metadata:
        name: vault-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

  # How vault is exposed
  service:
    type: ClusterIP
    ports:
      - name: vault
        port: 8200
        targetPort: 8200

  # Extra config (like your old vault.hcl)
  config:
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }

    storage "file" {
      path = "/vault/file"
    }

    disable_mlock = true

  # Auto-unseal (instead of manual init + unseal keys)
  externalConfig:
    policies:
      - name: default
        rules: path "*" { capabilities = ["create", "read", "update", "delete", "list", "sudo"] }
    auth:
      - type: kubernetes
        roles:
          - name: default
            bound_service_account_names: ["default"]
            bound_service_account_namespaces: ["vault"]
            policies: ["default"]
            ttl: 1h


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: vault
#   namespace: vault
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: vault
#   template:
#     metadata:
#       labels:
#         app: vault
#     spec:
#       serviceAccountName: vault
#       initContainers:
#       - name: vault-init
#         image: busybox:1.35
#         command: ['sh', '-c', 'chown -R 100:1000 /vault/data && chmod -R 755 /vault/data']
#         volumeMounts:
#         - name: vault-storage
#           mountPath: /vault/data
#         securityContext:
#           runAsUser: 0
#       securityContext:
#         runAsUser: 100
#         fsGroup: 1000
#       containers:
#       - name: vault
#         image: hashicorp/vault:1.15.2
#         args: ["vault", "server", "-config=/vault/config/vault.hcl"]
#         ports:
#         - containerPort: 8200
#           name: vault-port
#         - containerPort: 8201
#           name: cluster-port
#         env:
#         - name: VAULT_ADDR
#           value: "http://vault-service.vault.svc.cluster.local:8200"
#         - name: SKIP_SETCAP
#           value: "true"
#         volumeMounts:
#         - name: vault-storage
#           mountPath: /vault/data
#         - name: vault-config
#           mountPath: /vault/config
#         securityContext:
#           capabilities:
#             add:
#             - IPC_LOCK
#         readinessProbe:
#           httpGet:
#             path: /v1/sys/health?standbyok=true&sealedcode=200&uninitcode=200
#             port: 8200
#           initialDelaySeconds: 10
#           periodSeconds: 10
#         livenessProbe:
#           httpGet:
#             path: /v1/sys/health?standbyok=true&sealedcode=200&uninitcode=200
#             port: 8200
#           initialDelaySeconds: 30
#           periodSeconds: 30
#       volumes:
#       - name: vault-storage
#         persistentVolumeClaim:
#           claimName: vault-storage
#       - name: vault-config
#         configMap:
#           name: vault-config
